#!/usr/bin/env python3
"""Build a paper-spec.yaml draft from extracted evidence text.

This script intentionally creates a conservative draft. The model should edit the
YAML using paper evidence before scaffolding implementation code.
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path


def slugify(value: str, default: str = "paper") -> str:
    value = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return value[:80] or default


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def infer_title(text: str) -> str:
    for line in text.splitlines()[:80]:
        clean = line.strip().strip("# ")
        if 8 <= len(clean) <= 180 and not clean.lower().startswith(("abstract", "introduction", "arxiv")):
            return clean
    return "UNKNOWN"


def infer_method(title: str) -> str:
    words = re.findall(r"[A-Za-z0-9]+", title)
    if not words:
        return "paper"
    # Prefer acronym-like tokens or first two content words.
    acronyms = [w for w in words if len(w) >= 3 and w.upper() == w]
    if acronyms:
        return acronyms[0]
    return "-".join(words[:3])


def main() -> int:
    parser = argparse.ArgumentParser(description="Create paper-spec.yaml draft")
    parser.add_argument("evidence_md")
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    evidence_path = Path(args.evidence_md)
    text = read_text(evidence_path) if evidence_path.exists() else ""
    title = infer_title(text)
    method = infer_method(title)
    paper_slug = slugify(title)
    method_slug = slugify(method, paper_slug)
    implementation_slug = f"{method_slug}-reproduction"

    yaml = f"""# Generated by build_paper_spec.py. Edit with paper evidence before scaffolding.
paper:
  title: "{title}"
  year: "UNKNOWN"
  venue: "UNKNOWN"
  task: "TODO"
  modality: "TODO"
  method_name: "{method}"
  paper_slug: "{paper_slug}"
  implementation_slug: "{implementation_slug}"

architecture:
  type: "TODO"
  modules:
    - "TODO"
  inputs:
    - "TODO"
  outputs:
    - "TODO"
  loss_terms:
    - "TODO"

datasets:
  - name: "TODO"
    role: "train/eval"
    source_paper: "TODO"
    access: "TODO"
    preprocessing: "TODO"
    local_source_code: "TODO"
    data_processing_files:
      - "TODO"

training:
  seed: 42 # ASSUMPTION: debug default unless paper specifies.
  optimizer: "TODO"
  learning_rate: "TODO"
  batch_size: "TODO"
  epochs_or_steps: "TODO"
  scheduler: "TODO"
  augmentations:
    - "TODO"
  hardware: "TODO"

evaluation:
  metrics:
    - "TODO"
  protocol: "TODO"
  baselines:
    - "TODO"

evidence_status:
  code_found: false
  local_code_found: false
  reproducibility: "TODO"
  missing_fields:
    - "TODO"
  assumptions:
    - "ASSUMPTION: fields marked TODO must be filled from paper evidence before running training."
"""
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(yaml, encoding="utf-8")
    print("=== 执行脚本 ===")
    print("脚本：build_paper_spec.py")
    print(f"输入证据：{evidence_path}")
    print(f"输出文件：{out}")
    print(f"建议工程目录名：{implementation_slug}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
