#!/usr/bin/env python3
"""Generate a concise, structured PyTorch reproduction project from paper-spec.yaml.

The generated layout is intentionally close to many small/medium research repos:
main.py + config.py + run.py at the root, with data/, models/, engine/ and utils/
subpackages. It avoids multiple YAML configs, shell scripts, and a separate losses
package by default.
"""
from __future__ import annotations

import argparse
import re
import shutil
from pathlib import Path


def parse_simple_yaml(path: Path) -> dict[str, str]:
    """Tiny YAML-ish parser for scalar values used by this skill.

    This avoids external dependencies. It is not a general YAML parser.
    """
    data: dict[str, str] = {}
    stack: list[str] = []
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        indent = len(raw) - len(raw.lstrip(" "))
        line = raw.strip()
        if ":" not in line or line.startswith("-"):
            continue
        key, value = line.split(":", 1)
        key = key.strip()
        value = value.strip().strip('"\'')
        level = indent // 2
        stack = stack[:level]
        stack.append(key)
        if value:
            data[".".join(stack)] = value.split(" # ")[0].strip().strip('"\'')
    return data


def slugify(value: str, default: str = "paper") -> str:
    value = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return value[:80] or default


def class_name(value: str, default: str = "PaperModel") -> str:
    words = re.findall(r"[a-zA-Z0-9]+", value)
    if not words:
        return default
    name = "".join(w[:1].upper() + w[1:] for w in words)
    if name and name[0].isdigit():
        name = "Paper" + name
    return name or default


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Scaffold concise structured PyTorch reproduction project")
    parser.add_argument("paper_spec")
    parser.add_argument("--out", default="")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    spec_path = Path(args.paper_spec)
    if not spec_path.exists():
        print(f"错误：paper spec 不存在：{spec_path}")
        return 2

    spec = parse_simple_yaml(spec_path)
    title = spec.get("paper.title", "UNKNOWN")
    method = spec.get("paper.method_name") or spec.get("paper.task") or "paper"
    implementation_slug = spec.get("paper.implementation_slug") or f"{slugify(method, 'paper')}-reproduction"
    out = Path(args.out) if args.out else (spec_path.parent / implementation_slug)
    model_cls = class_name(method)

    if out.exists() and any(out.iterdir()) and not args.force:
        print(f"错误：输出目录已存在且非空：{out}")
        print("为避免覆盖，不会生成。请指定新目录或手动清理。")
        return 3
    out.mkdir(parents=True, exist_ok=True)
    (out / "repro-docs").mkdir(parents=True, exist_ok=True)

    shutil.copyfile(spec_path, out / "repro-docs" / "paper-spec.yaml")

    for pkg in ["data", "models", "engine", "utils"]:
        write(out / pkg / "__init__.py", "")

    write(out / "repro-docs" / "requirements.txt", """torch
numpy
tqdm
""")

    write(out / "README.md", f"""# {title} - Reproduction Scaffold

This project was generated by `paper-repro-triage` because no official/local main-paper source code was found.
It is a conservative PyTorch scaffold, not a claim of successful reproduction.

## Layout

- `main.py`: command-line entrypoint.
- `config.py`: argparse defaults and hyperparameters.
- `run.py`: dispatches preprocess/train/eval/inference by mode.
- `data/`: dataset loading and preprocessing.
- `models/`: paper model definition.
- `engine/`: training and evaluation loops.
- `utils/`: metrics, seed, path and JSON helpers.

## repro-docs

- `requirements.txt`: minimal dependency list.
- `paper-spec.yaml`: structured paper evidence used to generate this scaffold; it is not the training config.
- `evidence-map.md`: mapping from generated code files to paper evidence, dataset-code evidence or explicit assumptions.
- `repro-notes.md`: limitations, missing details and manual checks before real training.

## Commands

```cmd
python -m pip install -r repro-docs/requirements.txt
python main.py --mode preprocess --dataset paper --data_root ./data
python main.py --mode train --dataset paper --data_root ./data
python main.py --mode eval --checkpoint outputs/best.pt
```

## Safety notes

- This scaffold does not download datasets automatically.
- This scaffold does not install dependencies automatically.
- Paper-missing details are marked as `ASSUMPTION` or `TODO`.
- Run small smoke tests before real training.
""")

    write(out / "repro-docs" / "repro-notes.md", f"""# Reproduction Notes

This file records what is still uncertain or unverified. It is the place for reproduction limitations, assumptions, missing data, and manual checks. Do not treat this scaffold as a completed paper reproduction until these notes are resolved.

## Status

- Source code found: false
- Local main-paper source code found: false
- Generated implementation directory: `{out.name}`

## Important limitations

- This code is a scaffold generated from paper evidence and explicit assumptions.
- Do not report paper-level reproduction results until real data, dependencies, training and evaluation have been confirmed.

## Assumptions to verify

- Model dimensions and module details marked TODO.
- Dataset file layout and preprocessing steps marked TODO.
- Loss weights and scheduler details marked TODO unless paper-spec.yaml states them.
""")

    write(out / "repro-docs" / "evidence-map.md", """# Evidence Map

This file links generated code to paper evidence, dataset-code evidence, baseline-code evidence, or explicit assumptions. If a code choice is not supported by the paper, mark it as `ASSUMPTION` or `TODO`.

| Code file | Purpose | Paper evidence | Assumption / TODO |
|---|---|---|---|
| config.py | Command-line args and hyperparameters | paper-spec.yaml training/evaluation sections | TODO fields require paper evidence |
| main.py | CLI entrypoint | common research-code pattern | no paper-specific assumption |
| run.py | mode dispatch | paper task flow | no paper-specific assumption |
| data/dataset.py | Dataset loader | datasets/preprocessing section | TODO: actual file layout |
| data/preprocess.py | Data processing hooks | dataset-source-tracing results | TODO: adapt to actual dataset |
| models/model.py | Model definition | architecture section | ASSUMPTION if architecture details missing |
| engine/train.py | Training loop and loss/objective | training + loss_terms section | ASSUMPTION for missing hyperparameters |
| engine/evaluate.py | Evaluation loop | evaluation section | TODO: exact metrics if missing |
| utils/metrics.py | Metrics | evaluation metrics section | TODO if metric undefined |
""")

    write(out / "config.py", f'''import argparse


def build_parser():
    parser = argparse.ArgumentParser(description="{title} reproduction scaffold")
    parser.add_argument('--dataset', default='paper', help='dataset name or alias')
    parser.add_argument('--mode', default='train', choices=['preprocess', 'train', 'eval', 'inference'])
    parser.add_argument('--data_root', default='./data')
    parser.add_argument('--output_dir', default='./outputs')
    parser.add_argument('--checkpoint', default='', help='checkpoint path for eval/inference')
    parser.add_argument('--epochs', type=int, default=1, help='ASSUMPTION: debug default; replace with paper value')
    parser.add_argument('--batch_size', type=int, default=32, help='ASSUMPTION unless paper specifies')
    parser.add_argument('--lr', type=float, default=1e-3, help='ASSUMPTION unless paper specifies')
    parser.add_argument('--weight_decay', type=float, default=0.0)
    parser.add_argument('--num_workers', type=int, default=0)
    parser.add_argument('--seed', type=int, default=42)
    parser.add_argument('--gpu', default='0')
    parser.add_argument('--hidden_dim', type=int, default=256, help='TODO/ASSUMPTION: replace with paper value')
    parser.add_argument('--input_dim', type=int, default=128, help='TODO/ASSUMPTION: replace with dataset feature dimension')
    parser.add_argument('--output_dim', type=int, default=2, help='TODO/ASSUMPTION: replace with task output size')
    parser.add_argument('--alpha', type=float, default=1.0, help='optional paper-specific loss weight')
    parser.add_argument('--beta', type=float, default=1.0, help='optional paper-specific loss weight')
    return parser


def parse_args(argv=None):
    return build_parser().parse_args(argv)
''')

    write(out / "main.py", '''import os

from config import parse_args
from run import Run
from utils.common import set_seed


if __name__ == '__main__':
    args = parse_args()

    # Set visible GPU before creating CUDA contexts.
    os.environ['CUDA_VISIBLE_DEVICES'] = str(args.gpu)

    set_seed(args.seed)
    print(args)
    Run(args).main()
''')

    write(out / "run.py", '''from data.preprocess import preprocess
from engine.train import train
from engine.evaluate import evaluate


class Run:
    def __init__(self, args):
        self.args = args

    def main(self):
        if self.args.mode == 'preprocess':
            return preprocess(self.args)
        if self.args.mode == 'train':
            return train(self.args)
        if self.args.mode in {'eval', 'inference'}:
            return evaluate(self.args)
        raise ValueError(f'Unsupported mode: {self.args.mode}')
''')

    write(out / "utils" / "common.py", '''import json
import random
from pathlib import Path

import numpy as np
import torch


def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True


def get_device():
    return torch.device('cuda' if torch.cuda.is_available() else 'cpu')


def ensure_dir(path):
    Path(path).mkdir(parents=True, exist_ok=True)


def save_json(obj, path):
    path = Path(path)
    ensure_dir(path.parent)
    path.write_text(json.dumps(obj, ensure_ascii=False, indent=2), encoding='utf-8')
''')

    write(out / "data" / "dataset.py", '''# Data processing evidence:
# - Fill this section with dataset-source-tracing results.
# - If source repo processing files were found, list them here.
# TODO: Replace synthetic fallback with actual paper dataset parsing.

from pathlib import Path

import torch
from torch.utils.data import DataLoader, Dataset


class PaperDataset(Dataset):
    def __init__(self, root, split='train'):
        self.root = Path(root)
        self.split = split
        # TODO: Replace synthetic fallback with actual annotation/index loading.
        self.items = list(range(8))

    def __len__(self):
        return len(self.items)

    def __getitem__(self, index):
        # ASSUMPTION: vector input fallback for smoke checking.
        x = torch.randn(128)
        y = torch.tensor(index % 2, dtype=torch.long)
        return {'input': x, 'label': y}


def build_dataloader(args, split='train'):
    dataset = PaperDataset(args.data_root, split=split)
    shuffle = split == 'train'
    return DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=shuffle,
        num_workers=args.num_workers,
    )
''')

    write(out / "data" / "preprocess.py", '''from pathlib import Path


# TODO: Implement dataset-specific preprocessing based on paper evidence and
# dataset-source-tracing results. Do not download restricted datasets here.

def preprocess(args):
    data_root = Path(args.data_root)
    data_root.mkdir(parents=True, exist_ok=True)
    print(f'Preprocess placeholder. Data root: {data_root}')
    print('TODO: add annotation conversion, tokenizer/vocab construction, frame extraction, or feature extraction.')
''')

    write(out / "models" / "model.py", f'''# Model evidence:
# - Method name from paper-spec: {method}
# - TODO: Replace fallback MLP with paper-specific architecture.

from torch import nn


class {model_cls}(nn.Module):
    def __init__(self, args):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(args.input_dim, args.hidden_dim),
            nn.ReLU(),
            nn.Linear(args.hidden_dim, args.output_dim),
        )

    def forward(self, batch):
        x = batch['input']
        return self.net(x)


def build_model(args):
    return {model_cls}(args)
''')

    write(out / "utils" / "metrics.py", '''import torch


def accuracy(logits, labels):
    # TODO: Replace or extend with exact paper metrics.
    preds = torch.argmax(logits, dim=-1)
    return (preds == labels).float().mean().item()
''')

    write(out / "engine" / "train.py", '''import torch
from torch import nn
from torch.optim import Adam
from tqdm import tqdm

from data.dataset import build_dataloader
from models.model import build_model
from utils.common import ensure_dir, get_device
from utils.metrics import accuracy


def build_criterion(args):
    # TODO: Replace with paper-specific objective if different.
    # Keep loss here unless the paper has a complex reusable loss module.
    return nn.CrossEntropyLoss()


def train(args):
    device = get_device()
    ensure_dir(args.output_dir)

    train_loader = build_dataloader(args, split='train')
    model = build_model(args).to(device)
    criterion = build_criterion(args)
    optimizer = Adam(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)

    best_path = f'{args.output_dir}/best.pt'
    for epoch in range(args.epochs):
        model.train()
        total_loss = 0.0
        total_acc = 0.0
        steps = 0
        for batch in tqdm(train_loader, desc=f'epoch {epoch + 1}/{args.epochs}'):
            batch = {k: v.to(device) if hasattr(v, 'to') else v for k, v in batch.items()}
            logits = model(batch)
            loss = criterion(logits, batch['label'])
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            total_loss += loss.item()
            total_acc += accuracy(logits.detach(), batch['label'])
            steps += 1

        print({'epoch': epoch + 1, 'loss': total_loss / max(steps, 1), 'accuracy': total_acc / max(steps, 1)})
        torch.save({'model': model.state_dict(), 'args': vars(args)}, best_path)

    print(f'Saved checkpoint: {best_path}')
''')

    write(out / "engine" / "evaluate.py", '''import torch

from data.dataset import build_dataloader
from models.model import build_model
from utils.common import get_device, save_json
from utils.metrics import accuracy


def evaluate(args):
    device = get_device()
    loader = build_dataloader(args, split='test')
    model = build_model(args).to(device)

    if args.checkpoint:
        ckpt = torch.load(args.checkpoint, map_location=device)
        state = ckpt.get('model', ckpt)
        model.load_state_dict(state, strict=False)
    else:
        print('WARNING: no checkpoint provided; evaluating randomly initialized model.')

    model.eval()
    scores = []
    with torch.no_grad():
        for batch in loader:
            batch = {k: v.to(device) if hasattr(v, 'to') else v for k, v in batch.items()}
            logits = model(batch)
            scores.append(accuracy(logits, batch['label']))

    result = {'accuracy_placeholder': sum(scores) / max(len(scores), 1)}
    save_json(result, f'{args.output_dir}/eval.json')
    print(result)
''')

    print("=== 执行脚本 ===")
    print("脚本：scaffold_repro_project.py")
    print(f"论文：{title}")
    print(f"方法：{method}")
    print(f"工程路径：{out}")
    print("结构：base layout (repro-docs/, main.py, config.py, run.py, data/, models/, engine/, utils/); can be extended when the paper requires")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
