name: wechat-article-extractor
version: 1.0.0
display_name: "WeChat Article Extractor"
description: >
  Extract WeChat public account (微信公众号) articles to clean Markdown.
  Handles bot-detection via automatic mirror site discovery.
triggers:
  phrases:
    - mp.weixin.qq.com
    - wechat article
    - 微信公众号
    - extract wechat
    - save wechat article
    - archive wechat
    - 提取公众号文章
    - 保存公众号文章
  patterns:
    - "mp\\.weixin\\.qq\\.com"
    - "weixin.*article"
    - "公众号.*文章"
owner: any
tools_required:
  - web_fetch
  - web_search
  - exec
tools_optional:
  - browser
dependencies:
  python: ">=3.8"
  system:
    - curl
