#!/usr/bin/env python3
"""
Douyin Automation Setup Wizard - Full bootstrap.
Handles: clone backend → install deps → configure paths → health check.
Cross-platform (Windows/macOS/Linux).
"""

import json
import os
import re
import subprocess
import sys
from pathlib import Path

SKILL_DIR = Path(__file__).resolve().parent.parent
CONFIG_FILE = SKILL_DIR / "CONFIG.md"
BACKEND_REPO = "https://github.com/HNC87/douyin-agent-master.git"
SKILL_REPO = "https://github.com/HNC87/douyin-automation-skill.git"


def run(cmd, cwd=None, timeout=60, check=False):
    """Run shell command, return (success, stdout+stderr)."""
    try:
        r = subprocess.run(
            cmd, shell=True, cwd=cwd,
            capture_output=True, text=True, timeout=timeout
        )
        out = (r.stdout + "\n" + r.stderr).strip()
        if r.returncode == 0:
            return True, out
        return False, out
    except subprocess.TimeoutExpired:
        return False, "Command timed out"
    except Exception as e:
        return False, str(e)


def find_git_auth():
    """Get GitHub auth token if available."""
    # Check gh CLI
    ok, out = run("gh auth token 2>/dev/null")
    if ok and out.strip():
        return out.strip()

    # Check environment
    for env in ["GITHUB_TOKEN", "GH_TOKEN"]:
        t = os.environ.get(env, "")
        if t:
            return t

    # Check git credential store
    cfg = os.path.expanduser("~/.git-credentials")
    if Path(cfg).exists():
        content = Path(cfg).read_text()
        m = re.search(r"https://([^:]+):([^@]+)@", content)
        if m:
            return m.group(2)

    return None


def git_clone_with_auth(url, dest, depth=1):
    """Clone using auth token if available."""
    token = find_git_auth()
    if token:
        auth_url = url.replace("https://", f"https://{token}@")
    else:
        auth_url = url

    # Try with auth first
    ok, out = run(f'git clone {"--depth 1" if depth > 1 else ""} {auth_url} "{dest}"', timeout=120)
    if ok:
        return True, out

    # Fallback: try without auth (public repo)
    if token:
        ok2, out2 = run(f'git clone {"--depth 1" if depth > 1 else ""} {url} "{dest}"', timeout=120)
        return ok2, out2
    return ok, out


def find_project():
    """Find existing douyin-agent-master."""
    home = Path.home()
    candidates = [
        home / "douyin" / "douyin-agent-master",
        home / "douyin-agent-master",
        Path("D:/douyin/douyin-agent-master"),
        home / "projects" / "douyin-agent-master",
        home / "Documents" / "douyin-agent-master",
        home / "dev" / "douyin-agent-master",
        home / "code" / "douyin-agent-master",
    ]
    for p in candidates:
        if p.is_dir() and (p / "backend").exists():
            return p.parent
    return None


def find_creator_tools():
    """Find existing douyin-creator-tools."""
    home = Path.home()
    for base in [home / ".openclaw", home / ".qclaw", home]:
        ct = base / "douyin-creator-tools"
        if ct.is_dir():
            return ct
        ct2 = base / "workspace" / "douyin-creator-tools"
        if ct2.is_dir():
            return ct2
    return None


def check_chrome_cdp(port=9222):
    """Check if Chrome with remote debugging is accessible."""
    import urllib.request
    try:
        r = urllib.request.urlopen(f"http://localhost:{port}/json", timeout=3)
        data = json.loads(r.read())
        return True, f"Chrome CDP active (port {port}), {len(data)} tabs"
    except Exception:
        return False, f"Chrome CDP not accessible on port {port}"


def check_backend(port=8080):
    """Check if backend API is running."""
    import urllib.request
    try:
        r = urllib.request.urlopen(f"http://localhost:{port}/health", timeout=3)
        return True, f"Backend API active (port {port})"
    except Exception:
        return False, f"Backend API not running on port {port}"


def read_config():
    if not CONFIG_FILE.exists():
        return {}
    text = CONFIG_FILE.read_text(encoding="utf-8")
    m = re.search(r"```json\s*([\s\S]*?)\s*```", text)
    if m:
        try:
            return json.loads(m.group(1))
        except json.JSONDecodeError:
            return {}
    return {}


def write_config(config):
    lines = [
        "# Douyin Automation Configuration",
        "",
        f"> Auto-generated by setup.py on {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M')}.",
        "> Run `python scripts/setup.py` to reconfigure.",
        "",
        "```json",
        json.dumps(config, indent=2, ensure_ascii=False),
        "```",
    ]
    CONFIG_FILE.write_text("\n".join(lines), encoding="utf-8")
    return CONFIG_FILE


def generate_config(douyin_home, creator_tools=None, cdp_port=9222,
                   agent_port=8080, gateway="http://127.0.0.1:28789"):
    dh = Path(douyin_home)
    agent_backend = dh / "douyin-agent-master" / "backend"
    ct = Path(creator_tools) if creator_tools else Path.home() / ".openclaw" / "douyin-creator-tools"
    return {
        "douyin_home": str(dh),
        "agent_backend": str(agent_backend),
        "orchestrator": str(dh / "orchestrator"),
        "chatgroup_db": str(agent_backend / "app" / "chatgroup.db"),
        "uploads_dir": str(agent_backend / "uploads"),
        "cookies_file": str(agent_backend / "douyin_cookies.json"),
        "creator_tools": str(ct),
        "comments_output": str(ct / "comments-output"),
        "chrome_cdp_port": cdp_port,
        "agent_port": agent_port,
        "openclaw_gateway": gateway,
        "openclaw_model": "openclaw/default",
    }


def validate(config):
    """Validate paths and report status."""
    print("\n=== Validation ===")
    checks = {
        "Backend directory": Path(config["agent_backend"]),
        "Orchestrator": Path(config["orchestrator"]),
        "Chatgroup DB": Path(config["chatgroup_db"]),
        "Creator tools": Path(config["creator_tools"]),
    }
    results = []
    for name, path in checks.items():
        ok = path.exists()
        tag = "OK" if ok else "MISS"
        print(f"  [{tag:4}] {name}: {path}")
        results.append(ok)

    # Service checks
    ok_cdp, msg_cdp = check_chrome_cdp(config["chrome_cdp_port"])
    tag = "OK" if ok_cdp else "MISS"
    print(f"  [{tag:4}] Chrome CDP ({msg_cdp})")

    ok_api, msg_api = check_backend(config["agent_port"])
    tag = "OK" if ok_api else "MISS"
    print(f"  [{tag:4}] Backend API ({msg_api})")

    return all(results)


def main():
    print("=" * 60)
    print("  Douyin Automation - Setup Wizard")
    print("=" * 60)
    print(f"OS: {sys.platform}  |  Python: {sys.version.split()[0]}")
    print(f"Home: {Path.home()}")
    print()

    existing = read_config()

    # Step 1: Find or clone backend
    print("=== Step 1: Douyin Backend ===")
    project = find_project()

    if project:
        print(f"  [FOUND] {project}")
    else:
        print(f"  [NEW] Cloning from GitHub...")
        home = Path.home()
        dest = home / "douyin" / "douyin-agent-master"
        dest.parent.mkdir(parents=True, exist_ok=True)

        ok, out = git_clone_with_auth(BACKEND_REPO, str(dest.parent))
        if ok:
            # Rename if cloned as douyin-agent-master directly
            actual = home / "douyin-agent-master"
            if actual.is_dir() and not dest.is_dir():
                dest = actual
            print(f"  [OK] Cloned to: {dest}")
            project = dest
        else:
            print(f"  [WARN] Clone failed: {out[:200]}")
            print(f"  Manual: git clone {BACKEND_REPO} ~/douyin/")
            print(f"  Or download from: https://github.com/HNC87/douyin-agent-master")
            # Still prompt for manual path
            manual = input("\n  Enter path to douyin-agent-master: ").strip()
            if manual:
                project = Path(manual)
            else:
                print("  Skipped. You can run setup.py again later.")
                project = None

    # Step 2: Find or clone creator-tools
    print("\n=== Step 2: Creator Tools ===")
    ct = find_creator_tools()
    if ct:
        print(f"  [FOUND] {ct}")
    else:
        print(f"  [NEW] Cloning creator-tools...")
        ct_dest = Path.home() / ".openclaw" / "douyin-creator-tools"
        ct_dest.parent.mkdir(parents=True, exist_ok=True)
        ok, out = git_clone_with_auth(
            "https://github.com/HNC87/douyin-automation-skill.git",
            str(ct_dest.parent / "douyin-automation-skill")
        )
        if ok:
            # Creator tools are in the skill repo
            src = ct_dest.parent / "douyin-automation-skill" / "assets"
            if src.exists():
                import shutil
                ct_dest.mkdir(parents=True, exist_ok=True)
                for f in src.iterdir():
                    if f.suffix in [".mjs", ".js"]:
                        shutil.copy(f, ct_dest / f.name)
                print(f"  [OK] Copied to: {ct_dest}")
            ct = ct_dest
        else:
            print(f"  [WARN] Could not auto-clone: {out[:200]}")
            print(f"  Manual: git clone {SKILL_REPO} ~/.openclaw/douyin-creator-tools")
            ct = Path.home() / ".openclaw" / "douyin-creator-tools"

    # Step 3: Configure
    if project:
        print("\n=== Step 3: Configuration ===")
        defaults = {
            "cdp": existing.get("chrome_cdp_port", 9222),
            "agent": existing.get("agent_port", 8080),
            "gateway": existing.get("openclaw_gateway", "http://127.0.0.1:28789"),
        }

        cdp = input(f"  Chrome CDP port [{defaults['cdp']}]: ").strip()
        agent = input(f"  Backend API port [{defaults['agent']}]: ").strip()
        gw = input(f"  OpenClaw Gateway [{defaults['gateway']}]: ").strip()

        config = generate_config(
            project,
            ct,
            int(cdp) if cdp else defaults["cdp"],
            int(agent) if agent else defaults["agent"],
            gw if gw else defaults["gateway"],
        )
        write_config(config)
        print(f"\n  [OK] Config saved: {CONFIG_FILE}")

        # Step 4: Validate
        ok = validate(config)

        # Step 5: Install dependencies
        print("\n=== Step 4: Dependencies ===")
        req = project / "douyin-agent-master" / "backend" / "requirements.txt"
        if req.exists():
            print(f"  Installing Python deps from {req}...")
            ok_deps, out_deps = run(f'"{sys.executable}" -m pip install -r "{req}"', timeout=120)
            if ok_deps:
                print(f"  [OK] Dependencies installed")
            else:
                print(f"  [WARN] Some deps may have issues: {out_deps[:200]}")
        else:
            print(f"  [SKIP] No requirements.txt found")

        # Step 5: Quick start guide
        print("\n=== Next Steps ===")
        if ok:
            print("  All checks passed!")
            print("  Start backend:   python scripts/start-backend.py")
            print("  Run pipeline:    python scripts/run-pipeline.py")
            print("  Health check:   python scripts/status-check.py")
        else:
            print("  Some paths missing. Check your setup.")
            print("  Start Chrome with: chrome.exe --remote-debugging-port=9222")
            print("  Then run: python scripts/start-backend.py")

    else:
        print("\n  [DONE] Skipped backend setup.")
        print("  Run `python scripts/setup.py` again once you have the backend.")


if __name__ == "__main__":
    main()
