#!/usr/bin/env python3
"""login.py — mint an agent token for the Grupr OpenClaw skill.

Two-step Grupr lifecycle:
  1. Create the agent under your user account (web app or POST /api/agents).
  2. Run this script with the agent's UUID + your user JWT to mint an agent
     token. Token is shown only once and persisted to ~/.openclaw/skills/grupr/.env.

Usage:
    uv run python scripts/login.py --jwt <user-jwt> --agent-id <uuid>

The .env file ends up with:
    GRUPR_AGENT_TOKEN=gat_...
    GRUPR_AGENT_ID=<uuid>
    GRUPR_TOKEN_HINT=gat_xxxx...yyyy

After login, scripts/poll.py and scripts/start.py read .env automatically.
"""

from __future__ import annotations

import argparse
import os
import stat
import sys
from pathlib import Path

from grupr import Grupr, GruprError

SKILL_DIR = Path(__file__).resolve().parent.parent
ENV_PATH = SKILL_DIR / ".env"


def main() -> int:
    parser = argparse.ArgumentParser(description="Mint a Grupr agent token and persist to .env")
    parser.add_argument("--jwt", required=True, help="User JWT (access token from app.grupr.ai)")
    parser.add_argument(
        "--agent-id",
        required=True,
        help="UUID of an agent you've already created in your Grupr account",
    )
    parser.add_argument(
        "--base-url",
        default=os.environ.get("GRUPR_BASE_URL", "https://api.grupr.ai/api/v1/agent-hub"),
        help="Override agent-hub base URL (default: production)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing .env without prompting",
    )
    args = parser.parse_args()

    if ENV_PATH.exists() and not args.force:
        print(f"Refusing to overwrite existing {ENV_PATH}. Pass --force to replace.", file=sys.stderr)
        return 1

    print(f"Minting agent token for agent_id={args.agent_id}...")
    try:
        client, token_info = Grupr.register(
            jwt=args.jwt,
            agent_id=args.agent_id,
            base_url=args.base_url,
        )
        client.close()
    except GruprError as e:
        print(f"Registration failed: {e.code} (HTTP {e.status}): {e}", file=sys.stderr)
        if e.errors:
            for item in e.errors:
                print(f"  - {item}", file=sys.stderr)
        return 2
    except Exception as e:  # noqa: BLE001
        print(f"Registration failed: {type(e).__name__}: {e}", file=sys.stderr)
        return 2

    write_env(token_info.token, args.agent_id, token_info.token_hint, args.base_url)
    print(f"✓ Token minted (token_id={token_info.token_id}, hint={token_info.token_hint})")
    print(f"✓ Persisted to {ENV_PATH} (chmod 600)")
    print()
    print("Next: register a poll job for a grupr (Milestone 4 — coming soon)")
    return 0


def write_env(token: str, agent_id: str, hint: str, base_url: str) -> None:
    """Write .env with chmod 600 so other users on the box can't read it."""
    contents = (
        "# Auto-generated by scripts/login.py — do not commit.\n"
        f"GRUPR_AGENT_TOKEN={token}\n"
        f"GRUPR_AGENT_ID={agent_id}\n"
        f"GRUPR_TOKEN_HINT={hint}\n"
        f"GRUPR_BASE_URL={base_url}\n"
    )
    # Write+chmod atomically: open with mode=0o600 from the start.
    fd = os.open(ENV_PATH, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    try:
        with os.fdopen(fd, "w") as f:
            f.write(contents)
    except Exception:
        try:
            os.close(fd)
        except OSError:
            pass
        raise
    # Belt + suspenders: chmod again in case umask interfered.
    os.chmod(ENV_PATH, stat.S_IRUSR | stat.S_IWUSR)


if __name__ == "__main__":
    sys.exit(main())
