---
name: x-extract
description: Extract tweet content from x.com URLs without credentials using browser automation. Works without Twitter API credentials.
version: 1.0.0
triggers:
  - extract tweet
  - extract this tweet
  - get tweet content
  - download x.com link
  - download tweet
  - get x.com
  - fetch tweet
  - x.com/*/status/*
  - twitter.com/*/status/*
  - extract from x.com
  - extract from twitter
  - pull tweet
  - scrape tweet
---
