#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
==============================================================================
Disease-Specific Multi-Drug Cost-Effectiveness Analysis (CEA) Template
疾病多药成本效果分析（CEA）模板脚本

Usage / 使用说明:
  This script serves as the EXECUTABLE TEMPLATE generated by the
  disease-cea-auto Skill. The AI fills in disease-specific parameters
  (Section A) based on web-searched evidence, then runs the analysis.

  本脚本由 disease-cea-auto Skill 生成。AI 根据联网搜索的证据填入
  疾病特定参数（Section A），然后自动运行成本效果分析。

Author / 作者: disease-cea-auto Skill (LB Workspace)
Version / 版本: 1.0  |  Date / 日期: 2026-04-27
==============================================================================
"""

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
from copy import deepcopy

# ─────────────────────────────────────────────────────────────────────────────
# SECTION A: PARAMETERS  参数输入区
# AI fills this section based on disease and web-searched evidence.
# AI 根据具体疾病和联网搜索的证据填写此区域。
# ─────────────────────────────────────────────────────────────────────────────

# ── A0. Study Settings  研究设置 ──────────────────────────────────────────────
DISEASE_NAME_CN = "示例疾病"               # 疾病中文名 / Disease name (CN)
DISEASE_NAME_EN = "Example Disease"        # 疾病英文名 / Disease name (EN)
MODEL_TYPE      = "markov"                 # "markov" 或 "decision_tree"
CYCLE_LENGTH    = 1.0                      # 循环周期（年）/ Cycle length (years)
TIME_HORIZON    = 10                       # 时间范围（年）/ Time horizon (years)
DISCOUNT_RATE_C = 0.05                     # 费用贴现率 / Cost discount rate
DISCOUNT_RATE_E = 0.05                     # 效用贴现率 / Effectiveness discount rate
PERSPECTIVE     = "Healthcare system"      # 研究视角 / Study perspective

# ── A1. WTP Threshold  支付阈值 ───────────────────────────────────────────────
# AI should search latest China GDP per capita and update this value.
# AI 应联网搜索最新中国人均 GDP 并更新此数值。
GDP_PER_CAPITA  = 94000.0    # 元/人/年 / CNY per person per year (示例值 example)
GDP_DATA_YEAR   = 2024       # 统计年份 / Statistical year
GDP_SOURCE      = "国家统计局 / National Bureau of Statistics of China"
WTP_MULTIPLIER  = 1.0        # 1倍 GDP / 1× GDP per capita
WTP             = GDP_PER_CAPITA * WTP_MULTIPLIER  # QALY 支付阈值 / WTP threshold

# ── A2. Markov Health States  Markov 健康状态定义 ────────────────────────────
# Modify states to match the target disease.
# 请根据目标疾病修改健康状态。
STATES = [
    "Mild / 轻度",
    "Moderate / 中度",
    "Severe / 重度",
    "Death / 死亡",
]
ABSORBING_STATE = "Death / 死亡"   # 吸收态 / Absorbing state

# ── A3. Drugs  药物列表 ───────────────────────────────────────────────────────
# Each drug is a dict; "comparator" marks the reference arm.
# 每种药物为一个字典；"comparator": True 标记为对照组。
DRUGS = [
    {
        "name_cn":    "对照/安慰剂",
        "name_en":    "Comparator/Placebo",
        "comparator": True,
        # Annual drug cost / 年药品费用 (CNY)
        "drug_cost_annual": 0.0,
        # Annual disease management cost / 年疾病管理费用 (CNY)
        "mgmt_cost_annual": 20000.0,
        # Transition probability matrix (row = from, col = to) / 转换概率矩阵
        # Order matches STATES list above / 顺序与 STATES 列表一致
        "trans_prob": np.array([
            [0.70, 0.20, 0.05, 0.05],
            [0.00, 0.60, 0.25, 0.15],
            [0.00, 0.00, 0.55, 0.45],
            [0.00, 0.00, 0.00, 1.00],
        ]),
        # Utility values per state / 各状态效用值
        "utilities": [0.75, 0.55, 0.30, 0.00],
        # Grade 3/4 AE rate and per-episode cost / 3-4级不良反应率及处理费用
        "ae_rate":  0.05,
        "ae_cost":  3000.0,
    },
    {
        "name_cn":    "药物A",
        "name_en":    "Drug A",
        "comparator": False,
        "drug_cost_annual": 30000.0,
        "mgmt_cost_annual": 18000.0,
        "trans_prob": np.array([
            [0.75, 0.16, 0.05, 0.04],
            [0.00, 0.65, 0.22, 0.13],
            [0.00, 0.00, 0.60, 0.40],
            [0.00, 0.00, 0.00, 1.00],
        ]),
        "utilities": [0.77, 0.57, 0.32, 0.00],
        "ae_rate":  0.08,
        "ae_cost":  4000.0,
    },
    {
        "name_cn":    "药物B",
        "name_en":    "Drug B",
        "comparator": False,
        "drug_cost_annual": 60000.0,
        "mgmt_cost_annual": 15000.0,
        "trans_prob": np.array([
            [0.78, 0.14, 0.04, 0.04],
            [0.00, 0.68, 0.20, 0.12],
            [0.00, 0.00, 0.63, 0.37],
            [0.00, 0.00, 0.00, 1.00],
        ]),
        "utilities": [0.79, 0.59, 0.34, 0.00],
        "ae_rate":  0.10,
        "ae_cost":  4500.0,
    },
    {
        "name_cn":    "药物C",
        "name_en":    "Drug C",
        "comparator": False,
        "drug_cost_annual": 120000.0,
        "mgmt_cost_annual": 12000.0,
        "trans_prob": np.array([
            [0.80, 0.12, 0.04, 0.04],
            [0.00, 0.70, 0.18, 0.12],
            [0.00, 0.00, 0.65, 0.35],
            [0.00, 0.00, 0.00, 1.00],
        ]),
        "utilities": [0.81, 0.61, 0.36, 0.00],
        "ae_rate":  0.12,
        "ae_cost":  5000.0,
    },
]

# ── A4. Initial State Distribution  初始状态分布 ──────────────────────────────
INIT_STATE = np.array([0.40, 0.35, 0.25, 0.00])  # 各状态初始比例 / initial proportions

# ─────────────────────────────────────────────────────────────────────────────
# SECTION B: MARKOV ENGINE  Markov 模型计算引擎
# ─────────────────────────────────────────────────────────────────────────────

def discount_factor(rate: float, cycle: int) -> float:
    """
    计算贴现因子（半周期校正）
    Calculate discount factor with half-cycle correction.
    """
    return 1.0 / ((1 + rate) ** (cycle - 0.5))


def run_markov(drug: dict, n_cycles: int, init: np.ndarray,
               discount_r_c: float, discount_r_e: float) -> tuple:
    """
    运行 Markov 模型，返回总贴现费用和总贴现 QALY。
    Run Markov model; return total discounted cost and total discounted QALY.

    Parameters / 参数:
        drug        : drug parameter dict  药物参数字典
        n_cycles    : number of cycles      循环次数
        init        : initial state vector  初始状态分布向量
        discount_r_c: cost discount rate    费用贴现率
        discount_r_e: effect discount rate  效用贴现率

    Returns / 返回:
        (total_cost, total_qaly)  (总费用, 总QALY)
    """
    state_vec = init.copy()
    total_cost  = 0.0
    total_qaly  = 0.0
    utilities   = np.array(drug["utilities"])
    annual_cost = drug["drug_cost_annual"] + drug["mgmt_cost_annual"]
    ae_cost_ann = drug["ae_rate"] * drug["ae_cost"]

    for t in range(1, n_cycles + 1):
        df_c = discount_factor(discount_r_c, t)
        df_e = discount_factor(discount_r_e, t)

        # Alive proportion (exclude absorbing death state)
        # 存活比例（排除死亡吸收态）
        alive = 1.0 - state_vec[-1]

        # Cost this cycle / 本循环费用
        cycle_cost = alive * (annual_cost + ae_cost_ann) * CYCLE_LENGTH
        total_cost += cycle_cost * df_c

        # QALY this cycle / 本循环 QALY
        cycle_qaly = np.dot(state_vec, utilities) * CYCLE_LENGTH
        total_qaly += cycle_qaly * df_e

        # Transition to next cycle / 状态转移
        state_vec = state_vec @ drug["trans_prob"]

    return total_cost, total_qaly


# ─────────────────────────────────────────────────────────────────────────────
# SECTION C: DECISION TREE ENGINE  决策树计算引擎（慢性病请忽略）
# ─────────────────────────────────────────────────────────────────────────────

def run_decision_tree(drug: dict) -> tuple:
    """
    简化决策树模型：仅适用于急性/治愈性疾病。
    Simplified decision tree for acute/curative diseases only.

    Expects drug dict to have:
    / 药物字典需包含:
      "success_rate"   : float   治疗成功率 / treatment success rate
      "success_utility": float   成功时效用 / utility if success
      "failure_utility": float   失败时效用 / utility if failure
      "success_cost"   : float   成功路径总费用 / total cost if success
      "failure_cost"   : float   失败路径总费用 / total cost if failure
    """
    p = drug.get("success_rate", 0.5)
    qaly = p * drug.get("success_utility", 0.9) + (1 - p) * drug.get("failure_utility", 0.4)
    cost = (p * drug.get("success_cost", 5000) +
            (1 - p) * drug.get("failure_cost", 15000) +
            drug.get("drug_cost_annual", 0))
    return cost, qaly


# ─────────────────────────────────────────────────────────────────────────────
# SECTION D: MAIN ANALYSIS  主分析流程
# ─────────────────────────────────────────────────────────────────────────────

def run_cea(drugs: list, model_type: str = "markov") -> pd.DataFrame:
    """
    对所有药物运行 CEA，计算 ICER 和 NMB。
    Run CEA for all drugs; compute ICER and NMB.

    Returns / 返回:
        DataFrame with columns:
        药物名 | 总费用 | 总QALY | ΔC | ΔE | ICER | NMB | 是否成本效果
    """
    results = []
    comparator_cost  = None
    comparator_qaly  = None

    for drug in drugs:
        if model_type == "markov":
            cost, qaly = run_markov(
                drug, TIME_HORIZON, INIT_STATE,
                DISCOUNT_RATE_C, DISCOUNT_RATE_E
            )
        else:
            cost, qaly = run_decision_tree(drug)

        entry = {
            "药物名称 / Drug":      f"{drug['name_cn']} ({drug['name_en']})",
            "总费用 Total Cost (CNY)":    round(cost, 0),
            "总QALY Total QALY":          round(qaly, 4),
            "_is_comparator":             drug.get("comparator", False),
        }
        if drug.get("comparator"):
            comparator_cost = cost
            comparator_qaly = qaly

        results.append(entry)

    if comparator_cost is None:
        raise ValueError("No comparator drug found! Please set 'comparator': True for one drug.")

    # Calculate incremental values / 计算增量指标
    for r in results:
        if r["_is_comparator"]:
            r["ΔC 增量费用 (CNY)"]   = 0.0
            r["ΔE 增量QALY"]          = 0.0
            r["ICER (CNY/QALY)"]      = "—"
            r["NMB 净收益 (CNY)"]     = 0.0
            r["成本效果 Cost-Effective"] = "Reference / 参照"
        else:
            delta_c = r["总费用 Total Cost (CNY)"] - comparator_cost
            delta_e = r["总QALY Total QALY"]       - comparator_qaly
            nmb     = delta_e * WTP - delta_c

            r["ΔC 增量费用 (CNY)"]   = round(delta_c, 0)
            r["ΔE 增量QALY"]          = round(delta_e, 4)
            r["ICER (CNY/QALY)"]      = (
                f"{round(delta_c / delta_e, 0):,.0f}" if abs(delta_e) > 1e-9 else "∞"
            )
            r["NMB 净收益 (CNY)"]     = round(nmb, 0)
            r["成本效果 Cost-Effective"] = "Yes / 是" if nmb >= 0 else "No / 否"

    df = pd.DataFrame(results).drop(columns=["_is_comparator"])
    # Sort by NMB descending (comparator last) / 按 NMB 从大到小排序
    df_sorted = df.sort_values(
        by="NMB 净收益 (CNY)",
        ascending=False,
        key=lambda x: pd.to_numeric(x, errors="coerce").fillna(-1e18)
    ).reset_index(drop=True)
    return df_sorted


# ─────────────────────────────────────────────────────────────────────────────
# SECTION E: SENSITIVITY ANALYSIS  敏感性分析
# ─────────────────────────────────────────────────────────────────────────────

def one_way_sa(base_drugs: list, param_key: str,
               variations: list = (-0.20, 0.20),
               model_type: str = "markov") -> pd.DataFrame:
    """
    单因素敏感性分析。
    One-way sensitivity analysis on a specified parameter.

    Parameters / 参数:
        base_drugs  : original drug list         原始药物列表
        param_key   : parameter key to vary      待变动的参数键名
        variations  : relative variation range   相对变动范围（默认 ±20%）
        model_type  : "markov" or "decision_tree"
    """
    sa_records = []
    for var_pct in variations:
        drugs_copy = deepcopy(base_drugs)
        for d in drugs_copy:
            if param_key in d:
                original = d[param_key]
                if isinstance(original, (int, float)):
                    d[param_key] = original * (1 + var_pct)
                elif isinstance(original, np.ndarray):
                    d[param_key] = np.clip(original * (1 + var_pct), 0, 1)
                    # Re-normalize rows to sum to 1 / 重新归一化行使其和为1
                    row_sums = d[param_key].sum(axis=1, keepdims=True)
                    d[param_key] = d[param_key] / row_sums

        df_sa = run_cea(drugs_copy, model_type)
        df_sa.insert(0, "变动幅度 Variation", f"{var_pct:+.0%}")
        df_sa.insert(0, "分析参数 SA Param", param_key)
        sa_records.append(df_sa)

    return pd.concat(sa_records, ignore_index=True)


# ─────────────────────────────────────────────────────────────────────────────
# SECTION F: VISUALIZATION  可视化
# ─────────────────────────────────────────────────────────────────────────────

def plot_ce_plane(df_base: pd.DataFrame, wtp: float, filename: str = "ce_plane.png"):
    """
    绘制成本效果平面散点图（非参照组）。
    Plot cost-effectiveness plane for non-comparator drugs.
    """
    fig, ax = plt.subplots(figsize=(8, 6))
    colors = plt.cm.tab10.colors

    non_ref = df_base[df_base["ΔC 增量费用 (CNY)"] != 0].copy()
    for i, (_, row) in enumerate(non_ref.iterrows()):
        ax.scatter(row["ΔE 增量QALY"], row["ΔC 增量费用 (CNY)"],
                   color=colors[i % 10], s=120, zorder=5,
                   label=row["药物名称 / Drug"])
        ax.annotate(row["药物名称 / Drug"].split("(")[0],
                    (row["ΔE 增量QALY"], row["ΔC 增量费用 (CNY)"]),
                    textcoords="offset points", xytext=(8, 4), fontsize=8)

    # WTP slope line / WTP 斜率线
    x_range = np.linspace(non_ref["ΔE 增量QALY"].min() * 1.5,
                          non_ref["ΔE 增量QALY"].max() * 1.5, 100)
    ax.plot(x_range, x_range * wtp, "r--", linewidth=1.5,
            label=f"WTP = {wtp:,.0f} CNY/QALY\nWTP = {wtp:,.0f} 元/QALY")
    ax.axhline(0, color="grey", linewidth=0.8, linestyle=":")
    ax.axvline(0, color="grey", linewidth=0.8, linestyle=":")

    ax.set_xlabel("Incremental QALY  增量QALY", fontsize=11)
    ax.set_ylabel("Incremental Cost (CNY)  增量费用（元）", fontsize=11)
    ax.set_title(f"Cost-Effectiveness Plane\n成本效果平面 — {DISEASE_NAME_CN}/{DISEASE_NAME_EN}",
                 fontsize=12)
    ax.yaxis.set_major_formatter(mtick.FuncFormatter(lambda x, _: f"{x:,.0f}"))
    ax.legend(fontsize=8, loc="upper left")
    plt.tight_layout()
    plt.savefig(filename, dpi=150)
    plt.close()
    print(f"  [图表已保存 / Figure saved]: {filename}")


def plot_nmb_bar(df_base: pd.DataFrame, filename: str = "nmb_bar.png"):
    """
    绘制 NMB 条形图（从大到小排序，不含参照组）。
    Plot NMB bar chart (descending, excluding comparator).
    """
    non_ref = df_base[df_base["NMB 净收益 (CNY)"] != 0].copy()
    non_ref = non_ref.sort_values("NMB 净收益 (CNY)", ascending=False)

    labels = non_ref["药物名称 / Drug"].str.split("(").str[0].str.strip()
    values = non_ref["NMB 净收益 (CNY)"].values
    colors = ["steelblue" if v >= 0 else "tomato" for v in values]

    fig, ax = plt.subplots(figsize=(max(6, len(labels) * 1.5), 5))
    bars = ax.bar(range(len(labels)), values, color=colors, edgecolor="white", linewidth=0.5)
    ax.axhline(0, color="black", linewidth=1.0)
    ax.set_xticks(range(len(labels)))
    ax.set_xticklabels(labels, rotation=15, ha="right", fontsize=9)
    ax.set_xlabel("Drug / 药物", fontsize=11)
    ax.set_ylabel("Net Monetary Benefit (CNY) / 净货币收益（元）", fontsize=11)
    ax.set_title(f"Net Monetary Benefit Ranking (WTP = {WTP:,.0f} CNY/QALY)\n"
                 f"货币化净收益排名（支付阈值 = {WTP:,.0f} 元/QALY）", fontsize=12)
    ax.yaxis.set_major_formatter(mtick.FuncFormatter(lambda x, _: f"{x:,.0f}"))

    for bar, val in zip(bars, values):
        ax.text(bar.get_x() + bar.get_width() / 2,
                bar.get_height() + abs(max(values)) * 0.01,
                f"{val:,.0f}", ha="center", va="bottom", fontsize=8)

    plt.tight_layout()
    plt.savefig(filename, dpi=150)
    plt.close()
    print(f"  [图表已保存 / Figure saved]: {filename}")


# ─────────────────────────────────────────────────────────────────────────────
# SECTION G: REPORT PRINTER  报告打印
# ─────────────────────────────────────────────────────────────────────────────

DIVIDER = "=" * 80

def print_report(df_base: pd.DataFrame, df_sa: pd.DataFrame):
    """打印科学报告 / Print scientific report."""
    print(f"\n{DIVIDER}")
    print(f"  {DISEASE_NAME_CN} 多药成本效果分析报告")
    print(f"  Cost-Effectiveness Analysis Report — {DISEASE_NAME_EN} (Multiple Drugs)")
    print(DIVIDER)

    # 1. Background
    print("\n1. 研究背景 / Background")
    print(f"   疾病: {DISEASE_NAME_CN} / Disease: {DISEASE_NAME_EN}")
    print(f"   本研究采用 {MODEL_TYPE.upper()} 模型，从{PERSPECTIVE}视角，")
    print(f"   对该疾病常用治疗药物进行成本效果分析。")
    print(f"   This study applies a {MODEL_TYPE.upper()} model from the {PERSPECTIVE}")
    print(f"   perspective to conduct a cost-effectiveness analysis.")

    # 2. Methods
    print("\n2. 研究方法 / Methods")
    print(f"   模型类型 Model    : {MODEL_TYPE.upper()}")
    print(f"   时间范围 Horizon  : {TIME_HORIZON} years / 年")
    print(f"   循环周期 Cycle    : {CYCLE_LENGTH} year(s) / 年")
    print(f"   费用贴现 Cost DR  : {DISCOUNT_RATE_C*100:.1f}%")
    print(f"   效果贴现 Effect DR: {DISCOUNT_RATE_E*100:.1f}%")
    print(f"   WTP 支付阈值      : {WTP:,.0f} CNY/QALY (1× GDP per capita 1倍人均GDP)")
    print(f"   GDP 来源 Source   : {GDP_SOURCE} ({GDP_DATA_YEAR})")

    # 3. Base-Case Results
    print("\n3. 基础分析结果 / Base-Case Results")
    print("   NMB 从大到小排序 / Ranked by NMB (descending):")
    print()
    with pd.option_context("display.max_columns", None, "display.width", 200,
                           "display.float_format", "{:,.2f}".format):
        print(df_base.to_string(index=False))

    # 4. Sensitivity Analysis
    print("\n4. 敏感性分析 / Sensitivity Analysis (One-Way ±20%)")
    print()
    sa_display = df_sa[["分析参数 SA Param", "变动幅度 Variation",
                         "药物名称 / Drug", "NMB 净收益 (CNY)"]].copy()
    with pd.option_context("display.max_columns", None, "display.width", 200):
        print(sa_display.to_string(index=False))

    # 5. Conclusion
    print("\n5. 结论 / Conclusions")
    cost_eff = df_base[df_base["成本效果 Cost-Effective"] == "Yes / 是"]
    if cost_eff.empty:
        print("   基础分析中无药物达到成本效果阈值。")
        print("   No drug achieved cost-effectiveness at the specified WTP threshold.")
    else:
        best = cost_eff.iloc[0]["药物名称 / Drug"]
        print(f"   基础分析中，{best} 的货币化净收益最高，最具成本效果。")
        print(f"   In the base case, {best} has the highest NMB and is most cost-effective.")
    print(f"\n   WTP 阈值 = {WTP:,.0f} CNY/QALY (中国人均GDP {GDP_DATA_YEAR})")
    print(f"   WTP threshold = {WTP:,.0f} CNY/QALY (China GDP per capita {GDP_DATA_YEAR})")
    print(f"\n{DIVIDER}")


# ─────────────────────────────────────────────────────────────────────────────
# SECTION H: MAIN ENTRY  主程序入口
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print(f"\n{'─'*60}")
    print(f"  Disease CEA Analysis  疾病成本效果分析")
    print(f"  Disease / 疾病: {DISEASE_NAME_CN} / {DISEASE_NAME_EN}")
    print(f"  WTP = {WTP:,.0f} CNY/QALY  |  Horizon = {TIME_HORIZON}yr")
    print(f"{'─'*60}\n")

    # Run base-case / 运行基础分析
    print("[Step 1 / 步骤1] Running base-case analysis  运行基础分析...")
    df_base = run_cea(DRUGS, MODEL_TYPE)

    # Sensitivity analysis / 敏感性分析
    print("[Step 2 / 步骤2] Running sensitivity analysis  运行敏感性分析...")
    sa_params = ["drug_cost_annual", "utilities", "ae_rate"]
    sa_frames = []
    for param in sa_params:
        try:
            df_sa_part = one_way_sa(DRUGS, param, (-0.20, 0.20), MODEL_TYPE)
            sa_frames.append(df_sa_part)
        except Exception as e:
            print(f"  [SA warning] {param}: {e}")
    df_sa = pd.concat(sa_frames, ignore_index=True) if sa_frames else pd.DataFrame()

    # Visualizations / 可视化
    print("[Step 3 / 步骤3] Generating figures  生成图表...")
    plot_ce_plane(df_base, WTP, "ce_plane.png")
    plot_nmb_bar(df_base,       "nmb_bar.png")

    # Print report / 打印报告
    print("[Step 4 / 步骤4] Printing report  输出报告...\n")
    print_report(df_base, df_sa)

    print("\n[Done / 完成]  Results saved to: ce_plane.png  nmb_bar.png")
